version: "3"

services:
  db-postgres-evento:
    image: postgres:alpine
    ports:
      - "5435:5432"
    container_name: "db_postgres-evento"
    restart: always 
    volumes:
      - type: bind
        source: ./db-evento
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin

volumes:
  db-evento:
